use_frameworks!

target 'ZTuple_iOS_Tests' do
  pod 'ZTuple', :path => '../'
  
  pod 'Specta', '~> 1.0'
  pod 'Expecta', '~> 1.0'
  pod 'OCMock', '~> 3.4'
end

target 'ZTuple_macOS_Tests' do
    pod 'ZTuple', :path => '../'
    
    pod 'Specta', '~> 1.0'
    pod 'Expecta', '~> 1.0'
    pod 'OCMock', '~> 3.4'
end
